pipeline {
    agent any

    environment {
        MAVEN_HOME = 'C:/Program Files/apache-maven-3.9.10/bin'  // Set custom Maven path
        JAVA_HOME = 'C:/Program Files/Java/jdk-21'     // Set custom JDK path
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Lahamgegaurav/WONDRx.git'  // Git repository URL or local path
            }
        }

        stage('Build and Test') {
            steps {
                    bat '''
                    mvn clean test
                    '''  
            }
        }

        stage('Publish Reports') {
            steps {
                publishHTML(target: [
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'target/surefire-reports', // Location of your test reports
                    reportFiles: 'index.html',           // HTML report file generated by Maven Surefire
                    reportName: 'Test Report'
                ])
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'  // Runs regardless of success or failure (e.g., cleanup steps)
        }
    }
}
